CREATE DATABASE APPLICATION;
USE APPLICATION;

CREATE TABLE TEACHINGUNIT(
ID_T INT PRIMARY KEY,
ACRONYM VARCHAR(50),
QUALIFICATION VARCHAR(50),
ASSESSMENT VARCHAR(50),
DESCRIPTION_T VARCHAR(50)
);

CREATE TABLE STATEMENT(
ID_S INT PRIMARY KEY,
DESCRIPTION_S VARCHAR(50),
LEVEL_S ENUM('HIGH', 'AVERAGE', 'LOW'),
AVAILABLE BOOLEAN DEFAULT FALSE,
ROUTE VARCHAR(50)
);

CREATE TABLE TEACHINGUNIT_STATEMENT(
ID_T INT,
ID_S INT,
PRIMARY KEY(ID_T,ID_S),
FOREIGN KEY (ID_T) REFERENCES TEACHINGUNIT (ID_T),
FOREIGN KEY (ID_S) REFERENCES STATEMENT (ID_S)
);

CREATE TABLE EXAMCALL(
CALL_EXAM VARCHAR(50) PRIMARY KEY,
DESCRIPTION_EXAM VARCHAR(50),
DATE_EXAM DATE,
COURSE VARCHAR(50),
ID_S INT,
FOREIGN KEY (ID_S) REFERENCES STATEMENT (ID_S)
);